name: OCI Instance Provisioning

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Run Provisioning Script
        run: php index.php
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_CONTENT: ${{ secrets.OCI_KEY_CONTENT }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SHAPE: ${{ secrets.OCI_SHAPE }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
